services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app:delegated
      - /app/node_modules
    restart: unless-stopped
